name: Python application test with github actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Change directory
      run: |
        cd cloud-computing-foundations/scaffold
    - name: Install dependencies
      run: |
        cd cloud-computing-foundations/scaffold
        make install
    - name: Lint with pylint
      run: |
        cd cloud-computing-foundations/scaffold
        make lint
    - name: Test with pytest
      run: |
        cd cloud-computing-foundations/scaffold
        make test
    - name: Format Code with Black
      run: |
        cd cloud-computing-foundations/scaffold
        make format
        
